### ISSUE TITLE
wooden stick

### ISSUE THREAD

**Issue by thunderpwn** [storytime-studios/Forsaken_Future#12]
https://www.google.com/search?client=firefox-b-d&biw=1366&bih=632&tbm=isch&sa=1&ei=PBE8Xf--FYzamwWNzZqwAQ&q=post+apocalyptic+wood+stick&oq=post+apocalyptic+wood+stick&gs_l=img.3...9053.9053..10273...0.0..0.63.63.1......0....1..gws-wiz-img.CfHWvcIVPOU&ved=0ahUKEwj_zPzv3NTjAhUM7aYKHY2mBhYQ4dUDCAY&uact=5

**Comment by WuTangH** [comment]
models/items/baseball_bat added
